version: "3"
services:

  # Nuxt NODE process
  mn-board-frontend-node-prod:
    container_name: mn-board-frontend-node-prod
    build:
      context: .
      dockerfile: ./Dockerfile
    image: mn-board-frontend-node-prod
    restart: always
    ports:
      - "${PORT:-3000}:3000"
    environment:
      NODE_ENV: production
