version: "3"
services:

  # Nuxt NODE process
  mn-board-frontend:
    container_name: mn-board-frontend
    build:
      context: .
      dockerfile: Dockerfile
    image: mn-board-frontend
    ports:
      - "${PORT:-3000}:3000"
    environment:
      NODE_ENV: production
